### ISSUE TITLE
Missing moodle folder

### ISSUE THREAD

**Issue by dinism** [rschrenk/moodle-availability_gps#1]
Thanks for the plugin. VERY GOOD.

I found this error in my moodle instalation (folder is moodleescola)
![imagem](https://user-images.githubusercontent.com/14828021/142416031-3f60a6d2-a877-4e9d-b91d-37096aa6293a.png)

**Comment by rschrenk** [comment]
indeed, there was one variable missing in external function

https://github.com/center-for-learning-management/moodle-block_gps/commit/e5eac6cc8bf586c627855c135ed85c9b1ad6b6e2

fixed and uploaded new version, please update.

**Comment by rschrenk** [comment]
PS: You must update the block_gps-Plugin, not the availability!

**Comment by dinism** [comment]
THANKS a lot.
I'm a PT-PT tanslator and it is done in AMOS. Both.
