### ISSUE TITLE
Moodle Code Checker fixes

### ISSUE THREAD

**Issue by GGeorggg** [rschrenk/moodle-availability_gps#3]
Hallo @lassnj 

vermutlich musst prowebat noch Berechtigungen auf dieses Repository geben (mention geht nicht)

lg
Georg

**Comment by GGeorggg** [comment]
Hallo @lassnj 

kannst du proweb oder @rschrenk die yui javascript neu builden lassen (ich bekomme die Abhängigkeiten nicht gebacken, und für ihn ist es vermutlich nur ein Kommando - dann hätten wir hier ein funktionierenden Workflow) - gute Vorraussetzungen um das Plugin zu überarbeiten

Den check für code dokumentation und phpunit tests habe ich deaktiviert (Dokumentation fehlt größtenteils und PHPUnit Tests gibts keine)

danke
Georg

**Comment by prowebat** [comment]
@lassnj aus den Nachrichten lese ich kein To-Do raus.

**Comment by lassnj** [comment]
@prowebat 

> kannst du proweb die yui javascript neu builden lassen (ich bekomme die Abhängigkeiten nicht gebacken

also bitte yui javascript neu builden. Danke!

**Comment by prowebat** [comment]
@GGeorggg 
ist erledigt
